name: CI
on:
  repository_dispatch:
    types:
      - webhook-1
      - webhook-2
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
jobs:
  msw-msvs:
    runs-on: windows-${{ matrix.vsversion }}
    name: wxMSW vs${{ matrix.vsversion }} ${{ matrix.configuration }} ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - configuration: 'Release'
            platform: 'x64'
            vsversion: 2019
    steps:

      
          
      - uses: lukka/get-cmake@latest

      - uses: actions/checkout@v3
        with:
          submodules: recursive


      - name: Checkout from Gitee
        run: |
          git clone https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/charlesabc/quick-print.git 

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: CMake
        shell: powershell
        run: |
          pwd
          dir 
          cd quick-print/build
          cmake ../ -G "Visual Studio 16 2019"

          # run CMake (additional options like -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE are possible)
          # it is recommended to specify the compiler version used for the build
          # cmake -S . -B cbuild/ -DCRASHPAD_BUILD_EXAMPLES=TRUE -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_C_COMPILER=cl.exe -DCMAKE_BUILD_TYPE=Release
          # cmake --build cbuild/ --config Release -- /p:Configuration=Release

      - name: Download External Lib
        run: |
          set PYTHONIOENCODING=utf-8
          cd quick-print/tools/external_lib
          pip install -r requirements.txt
          python download.py --arch x64 --build_types dbg
          python download.py --arch x64 --build_types rel
          ls ../../external/wxWidgets/
          echo "----------------------------------------------------------------------"
          ls ../../external/wxWidgets/win
          echo "----------------------------------------------------------------------"
          ls ../../external/wxWidgets/win//include
          echo "----------------------------------------------------------------------"
          ls ../../external/wxWidgets/win//include/wx
          
          
          


      - name: Build with MSBuild
        run: msbuild -m -t:Build -p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} quick-print/build/quick-print.sln


        
